"""init schema

Revision ID: 6bf5036f247d
Revises:
Create Date: 2025-11-28 21:30:48.535420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6bf5036f247d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", postgresql.CITEXT(), nullable=False),
        sa.Column("building", sa.Text(), nullable=False),
        sa.Column("floor", sa.SmallInteger(), nullable=False),
        sa.Column("room_number", sa.Text(), nullable=False),
        sa.Column("room_suffix", sa.Text(), nullable=True),
        sa.Column(
            "room_type",
            sa.Enum("lecture", "computer_lab", "practice", name="room_type"),
            nullable=False,
        ),
        sa.Column(
            "has_projector", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_rooms_code"),
    )
    op.create_index(
        "ix_rooms_bld_floor_num",
        "rooms",
        ["building", "floor", "room_number"],
        unique=False,
    )
    op.create_index(
        "ix_rooms_bld_floor_num_suf",
        "rooms",
        ["building", "floor", "room_number", "room_suffix"],
        unique=False,
    )
    op.create_index(
        "ix_rooms_building_floor", "rooms", ["building", "floor"], unique=False
    )
    op.create_table(
        "time_slots",
        sa.Column("slot_number", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.CheckConstraint(
            "start_time < end_time", name="ck_time_slots_start_before_end"
        ),
        sa.PrimaryKeyConstraint("slot_number"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("middle_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("teacher", "admin", "infra", name="user_role"),
            server_default="infra",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "entity_kind", sa.Enum("booking", name="entity_kind"), nullable=False
        ),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_booking", "audit_events", ["entity_kind", "entity_id"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.BigInteger(), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("slot_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_title", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", name="booking_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("last_edited_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["last_edited_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["slot_number"], ["time_slots.slot_number"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bookings_active_date_room",
        "bookings",
        ["booking_date", "room_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
        postgresql_include=["slot_number"],
    )
    op.create_index(
        "ix_bookings_room_date", "bookings", ["room_id", "booking_date"], unique=False
    )
    op.create_index(
        "ix_bookings_user", "bookings", ["user_id", "booking_date"], unique=False
    )
    op.create_index(
        "uq_active_booking",
        "bookings",
        ["room_id", "booking_date", "slot_number"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", postgresql.BYTEA(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="ux_refresh_hash"),
    )
    op.create_index("ix_refresh_user", "refresh_tokens", ["user_id"], unique=False)
    op.create_index(
        "ix_refresh_valid", "refresh_tokens", ["token_hash", "expires_at"], unique=False
    )
    op.create_table(
        "semester_slots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.BigInteger(), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.Column("slot_number", sa.SmallInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("group_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["slot_number"], ["time_slots.slot_number"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "room_id", "slot_date", "slot_number", name="uq_semester_slot"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("semester_slots")
    op.drop_index("ix_refresh_valid", table_name="refresh_tokens")
    op.drop_index("ix_refresh_user", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "uq_active_booking",
        table_name="bookings",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_bookings_user", table_name="bookings")
    op.drop_index("ix_bookings_room_date", table_name="bookings")
    op.drop_index(
        "ix_bookings_active_date_room",
        table_name="bookings",
        postgresql_where=sa.text("status = 'active'"),
        postgresql_include=["slot_number"],
    )
    op.drop_table("bookings")
    op.drop_index("ix_audit_booking", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("time_slots")
    op.drop_index("ix_rooms_building_floor", table_name="rooms")
    op.drop_index("ix_rooms_bld_floor_num_suf", table_name="rooms")
    op.drop_index("ix_rooms_bld_floor_num", table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
